language: go

go:
  - 1.7
  - 1.8
  - tip

services:
  - postgresql

before_script:
  - psql -c 'create database dbi;' -U postgres postgres

env:
  global:
    - PGDATABASE=dbi
    - PGUSER=postgres
    - PGHOST="127.0.0.1"

install:
  - go get gopkg.in/check.v1
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3

script:
  - go test -v -race -timeout 20s