language: go

go:
  - "1.11"

services:
  - postgresql
  - mysql

before_script:
  - psql -c 'create database dbi;' -U postgres postgres
  - mysql -u root -e 'CREATE DATABASE dbi;'

env:
  global:
    - PGDATABASE=dbi
    - PGUSER=postgres
    - PGHOST="127.0.0.1"
    - MYSQLUSER=root
    - GO111MODULE=on

script:
  - go test -v -race -timeout 30s v3/*.go
