language: go

go:
  - 1.8
  - 1.9

services:
  - postgresql

before_script:
  - psql -c 'create database dbi;' -U postgres postgres

env:
  global:
    - PGDATABASE=dbi
    - PGUSER=postgres
    - PGHOST="127.0.0.1"

install:
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - go get github.com/jackc/pgx

script:
  - go test -v -race -timeout 20s